# SITE CONFIGURATION
baseurl: ""
url: "0xln.pw"

# THEME-SPECIFIC CONFIGURATION
title: Infosec and Password Cracking Blog                                   # site's title
description: "Password cracking, infosec articles and assorted hackery"      # used by search engines
avatar: /assets/img/triangle.jpg                       # Empty for no avatar in navbar
favicon: /assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: 0xln  # Change Blog header text
header_feature_image: /assets/img/background.jpg
footer_text:

# Blog
excerpt: truncate                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: false                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: UA-148799411-1                                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname: false                                      # Your discus shortname for comments
cusdis_app_id: false                                          # Your cusdis data-app-id
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
